# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", inline: <<-SHELL

    # The Basics - RAWR!

    # Uncomment if you live in beautiful British Columbia
    # sed -i 's/archive\.ubuntu\.com/mirror\.it\.ubc\.ca/' /etc/apt/sources.list

    apt-get update
    apt-get -y upgrade
    apt-get -y install software-properties-common joe

    # Let's Do NGINX
    curl http://nginx.org/keys/nginx_signing.key | apt-key add -
    echo -e "deb http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx\ndeb-src http://nginx.org/packages/mainline/ubuntu/ `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list
    apt-get -y install nginx

    # Now Let's HHVM
    apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
    add-apt-repository "deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main"
    apt-get update
    apt-get -y install hhvm
    /usr/share/hhvm/install_fastcgi.sh
    update-rc.d hhvm defaults

    # Insert Our NGINX config TO RULE THE WORLDS!
    sed -i 's/sendfile on;/sendfile off;/' /etc/nginx/nginx.conf
    cp /vagrant/configs/default /etc/nginx/sites-available/default
    service nginx restart

  SHELL
end
